# Generated by Django 2.2.24 on 2025-03-12 16:40

from django.db import migrations
import phonenumbers


def formatting_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        try:
            phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')

            if phonenumbers.is_valid_number(phone_number):
                formatted_phone_number = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.E164)
                flat.owner_pure_phone = formatted_phone_number
            else:
                flat.owner_pure_phone = None

            flat.save()
        except phonenumbers.NumberParseException:
            flat.owner_pure_phone = None
            flat.save()


def revert_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        flat.owners_phonenumber = flat.owner_pure_phone
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(formatting_phone_number, revert_phone_number),
    ]
