# Generated by Django 2.2.24 on 2025-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250312_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_deprecated',
            field=models.ManyToManyField(related_name='flats', to='property.Owner', verbose_name='Собственники квартиры'),
        ),
    ]
