# Generated by Django 2.2.24 on 2025-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20250313_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(related_name='owned_flats', to='property.Owner', verbose_name='Собственники'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flat_owner',
            field=models.ManyToManyField(related_name='owner_flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
